books_app/urls.py
from django.urls import path, include
from books_app import views

app_name = "books_app"
urlpatterns = [
    path("", views.AddBook.as_view(), name="book_add"),
    path("book_list", views.BookList.as_view(), name="book_list"),
    path("update/<int:id>", views.BookUpdate.as_view(), name="book_update"),
    
]

central_library/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

books_app/models.py
from django.db import models

class Book(models.Model):
    book_id = models.AutoField(primary_key=True, unique=True)
    name = models.CharField(max_length=100)
    published = models.IntegerField()
    author = models.CharField(max_length=100)
    domain = models.CharField(max_length=200)
    is_available = models.BooleanField(default=False)

books_app/views.py
from django.http import JsonResponse
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import status
from rest_framework.renderers import TemplateHTMLRenderer
from django.shortcuts import redirect

from .models import Book
from .serializers import BookSerializer

class AddBook(APIView):

    renderer_classes = [TemplateHTMLRenderer]

    def get(self, request):
        return Response(template_name="book_add.html", status=status.HTTP_200_OK)

    def post(self, request):
        data = {
            "name": request.data.get("name"),
            "published": request.data.get("published"),
            "author": request.data.get("author"),
            "domain": request.data.get("domain"),
            "is_available": request.data.get("is_available", False),
        }

        serializer = BookSerializer(data=data)
        if(serializer.is_valid()):
            serializer.save()
            return redirect("books_app:book_list")
        
        error = {
            "error": "Invalid data"
        }
        return Response(data=error, template_name="book_add.html", status=status.HTTP_400_BAD_REQUEST)

class BookList(APIView):

    renderer_classes = [TemplateHTMLRenderer]

    def get(self, request):
        query_author = request.query_params.get("author")
        query_published = request.query_params.get("published")
        query_domain = request.query_params.get("domain")

        queried = False
        if(query_author):
            queried = True
            books = Book.objects.filter(author=query_author)
        else:
            books = Book.objects.all()
        
        if(query_published):
            queried = True
            books = books.filter(published=query_published)
        
        if(query_domain):
            queried = True
            books = books.filter(domain=query_domain)

        serializers = BookSerializer(books, many=True)
        data = {
            "results": serializers.data,
            "query": {
                "author": query_author if query_author else "",
                "published": query_published if query_published else "",
                "domain": query_domain if query_domain else ""
            },
            "queried": queried
        }
        return Response(data=data, template_name="book_list.html", status=status.HTTP_200_OK)

class BookUpdate(APIView):

    renderer_classes = [TemplateHTMLRenderer]

    def get(self, request, id):
        try:
            book = Book.objects.get(book_id=id)
        except Book.DoesNotExist:
            return Response(template_name="book_list.html", status=status.HTTP_404_NOT_FOUND)
        
        serializer = BookSerializer(book)
        return Response(data={"book": serializer.data}, template_name="book_edit.html", status=status.HTTP_200_OK)
    
    def post(self, request, id):
        try:
            book = Book.objects.get(book_id=id)
        except Book.DoesNotExist:
            return Response(template_name="book_list.html", status=status.HTTP_404_NOT_FOUND)

        data = {
            "name": request.data.get("name"),
            "published": request.data.get("published"),
            "author": request.data.get("author"),
            "domain": request.data.get("domain"),
            "is_available": request.data.get("is_available", False),
        }

        serializer = BookSerializer(book, data, partial=True)
        if(serializer.is_valid()):
            serializer.save()
        
        return redirect("books_app:book_list")
    
    def delete(self, request, id):
        try:
            book = Book.objects.get(book_id=id)
        except Book.DoesNotExist:
            return Response(template_name="book_list.html", status=status.HTTP_404_NOT_FOUND)
        
        book.delete()
        return Response(template_name="book_list.html", status=status.HTTP_200_OK)
        

books_app/templates/book_add.html
{% load rest_framework %}

<html lang="en">
    <head>
        <title>Add Book</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    </head>
    
    <body>
        <h1 class="text-center">Add Book</h1>
        <div class="container" style="width:50%; background-color: rgba(127, 143, 185, 0.842);">
            <form action="{% url 'books_app:book_add' %}" method="POST" enctype="multipart/form-data" id="bookAddForm">
                {% csrf_token %}
          
                <div class="form-group">
                  <label for="name">Book Name</label>
                  <input type="text" class="form-control" id="name" name="name" placeholder="Harry Potter" required>
                </div>
          
                <div class="form-group">
                  <label for="published">Published</label>
                  <input type="number" class="form-control" id="published" name="published" value="" placeholder="2022" required>
                </div>

                <div class="form-group">
                    <label for="author">Author</label>
                    <input type="text" class="form-control" id="author" name="author" placeholder="J. K. Rowling" required>
                </div>

                <div class="form-group">
                    <label for="domain">Domain</label>
                    <input type="text" class="form-control" id="domain" name="domain" placeholder="Fiction" required>
                </div>

                <div class="form-group">
                    <label for="is_available">Is Availabale</label>
                    <select class="form-control" id="is_available" name="is_available">
                        <option value="True">True</option>
                        <option value="False" selected>False</option>
                    </select>
                </div>
          
                <div>
                    <button type="submit" class="btn btn-primary">Upload</button>
                </div>
            </form>
        </div>
        <br>
        <div class="text-center">
            <a class="btn btn-primary" href="{% url 'books_app:book_list' %}">See all Books :)</a>
        </div>

    </body>
</html>

books_app/templates/book_edit.html
{% load rest_framework %}

<html lang="en">
    <head>
        <title>Add Book</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <script>
            function csrfcookie(name){
                var cookieValue = null;

                if (document.cookie && document.cookie !== '') {
                    var cookies = document.cookie.split(';');
                    for (var i = 0; i < cookies.length; i++) {
                        var cookie = cookies[i].trim();
                        if (cookie.substring(0, name.length + 1) === (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }

        </script>
    </head>
    
    <body>
        <h1 class="text-center">Edit Book</h1>
        <div class="container" style="width:50%; background-color: rgba(127, 143, 185, 0.842);">
            <form name="edit_form" action="{% url 'books_app:book_update' book.book_id %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
          
                <div class="form-group">
                  <label for="name">Book Name</label>
                  <input type="text" class="form-control" id="name" name="name" placeholder="Harry Potter" value="{{book.name}}" readonly>
                </div>
          
                <div class="form-group">
                  <label for="published">Published</label>
                  <input type="number" class="form-control" id="published" name="published" placeholder="2022" value="{{book.published}}" required>
                </div>

                <div class="form-group">
                    <label for="author">Author</label>
                    <input type="text" class="form-control" id="author" name="author" placeholder="J. K. Rowling" value="{{book.author}}" required>
                </div>

                <div class="form-group">
                    <label for="domain">Domain</label>
                    <input type="text" class="form-control" id="domain" name="domain" placeholder="Fiction" value="{{book.domain}}" required>
                </div>

                <div class="form-group">
                    <label for="is_available">Is Availabale</label>
                    <select class="form-control" id="is_available" name="is_available">
                        <option value="True">True</option>
                        <option value="False" selected>False</option>
                    </select>
                </div>
          
                <div>
                    <button type="submit" class="btn btn-primary">Upload</button>
                </div>
            </form>
        </div>
        <br>
        <div class="text-center">
            <a class="btn btn-primary" href="{% url 'books_app:book_list' %}">See all Books :)</a>
        </div>

    </body>
</html>

books_app/templates/book_list.html
{% load rest_framework %}

<html lang="en">
    <head>
        <title>Books List</title>
        <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1">
        <meta name="sviewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    </head>
    <style>
        #myBtn {
            display: block;
            position: fixed;
            bottom: 20px;
            right: 30px;
            z-index: 99;
            font-size: 18px;
            border: none;
            outline: none;
            background-color: red;
            color: white;
            cursor: pointer;
            padding: 15px;
            border-radius: 4px;
            }

        #myBtn:hover {
            background-color: #555;
        }
        /* .card-custom {
            max-width: 128px;
        } */
    </style>
    <body>
        <button onclick="topFunction()" id="myBtn" title="Go to top">Top</button>
        
        <h1 class="text-center">Books List</h1>
        <div class="text-center">
            <a class="btn btn-primary" href="{% url 'books_app:book_add' %}">Want to add a new Book :)</a>
        </div>

        <br>

        <div class="container" style="width:50%; background-color: rgba(127, 143, 185, 0.842);">
            <form name="edit_form" action="{% url 'books_app:book_list' %}" method="GET" enctype="multipart/form-data">
                {% csrf_token %}
          
                <div class="form-group">
                  <label for="author">Author</label>
                  <input type="text" class="form-control" id="author" name="author" placeholder="J. K. Rowling" value="{{query.author}}">
                </div>
          
                <div class="form-group">
                  <label for="published">Published</label>
                  <input type="number" class="form-control" id="published" name="published" placeholder="2022" value="{{query.published}}">
                </div>

                <div class="form-group">
                    <label for="domain">Domain</label>
                    <input type="text" class="form-control" id="domain" name="domain" placeholder="fiction" value="{{query.domain}}">
                  </div>

                <div>
                    <button type="submit" class="btn btn-primary">Apply Filter</button>
                </div>
            </form>
        </div>
        <br>
        <div class="text-center">
            <a class="btn btn-primary" href="{% url 'books_app:book_list' %}">See all Books :)</a>
        </div>

        {% if queried == True %}
            <h2 class="text-center">Search Results for query={{query}}</h2>            
        {% endif %}

        {% if results %}
            <div class="text-center">
            <div class="row row-cols-1 row-cols-md-3 g-4 m-5 pb-5">
                {% for book in results %}
                <div class="col">
                    <div class="card" style="max-width: 18rem;">
                        <div class="card-body">
                            <h5 class="card-title">{{book.name}}</h5>
                            <p class="card-text">Published: {{book.published}}</p>
                            <p class="card-text">Author: {{book.author}}</p>
                            <p class="card-text">Domain: {{book.domain}}</p>
                            <p class="card-text">isAvailable: {{book.is_available}}</p>

                            <a href="{% url 'books_app:book_update' book.book_id %}">
                                <input class="btn btn-primary" id="editBtn" type="button" value="Edit">
                            </a>

                            <input class="btn btn-danger" id="delBtn" onclick="deleteBook({{book.book_id}})" type="button" value="Delete">
                        </div>
                    </div>
                    <br>
                </div>
                {% endfor %}
            </div>
            </div>
        {% else %}
            {% if queried == True %}
                <h2 class="text-center">There are no search results for query={{query}}.</h2>
            {% endif %}
        {% endif %}

        <script>
            var mybutton = document.getElementById("myBtn");

            // When the user scrolls down 20px from the top of the document, show the button
            window.onscroll = function() {scrollFunction()};

            function scrollFunction() {
            if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
                mybutton.style.display = "block";
            } else {
                mybutton.style.display = "none";
            }
            }

            // When the user clicks on the button, scroll to the top of the document
            function topFunction() {
            document.body.scrollTop = 0;
            document.documentElement.scrollTop = 0;
            }

            function csrfcookie(name){
                var cookieValue = null;

                if (document.cookie && document.cookie !== '') {
                    var cookies = document.cookie.split(';');
                    for (var i = 0; i < cookies.length; i++) {
                        var cookie = cookies[i].trim();
                        if (cookie.substring(0, name.length + 1) === (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }

            var delbutton = document.getElementById("delBtn");
            function deleteBook(id) {
                var csrftoken = csrfcookie('csrftoken');
                var url = `/update/${id}`;
                fetch(url,{
                    method: 'DELETE',
                    credentials: 'same-origin',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': csrftoken,
                    }
                }).then(function(response){
                    location.href="/book_list";
                });
            }
        </script>
    </body>
</html>